# Generated by Django 5.1.7 on 2025-03-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='آدرس اینترنتی'),
        ),
    ]
