# Generated by Django 5.1.7 on 2025-03-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_user_is_active_alter_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='user', verbose_name='پروفایل'),
        ),
    ]
