# Generated by Django 5.1.7 on 2025-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_user_bio_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='توضیحات'),
        ),
    ]
