# Generated by Django 5.1.7 on 2025-03-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_remove_user_bio_remove_user_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره همراه')),
                ('code', models.CharField(max_length=6, verbose_name='کد تایید')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
