# Generated by Django 5.1.7 on 2025-03-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'رمز یک بار مصرف', 'verbose_name_plural': 'رمزهای یک بار مصرف'},
        ),
    ]
