# Generated by Django 5.1.7 on 2025-03-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_alter_otp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='user_default_profile.jpg', upload_to='user', verbose_name='پروفایل'),
        ),
    ]
