# Generated by Django 5.1.7 on 2025-03-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, default='user_default_profile.png', null=True, upload_to='user', verbose_name='پروفایل'),
        ),
    ]
