# Generated by Django 5.1.7 on 2025-03-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_alter_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified_email',
            new_name='email_verified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verified_phone',
            new_name='phone_verified',
        ),
    ]
