# Generated by Django 5.1.7 on 2025-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_rename_verified_email_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
