# Generated by Django 5.1.7 on 2025-03-16 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_author_alter_blog_baner_alter_blog_cates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_sub',
            new_name='is_reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='sub',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='blog.comment', verbose_name='در پاسخ به'),
        ),
    ]
