# Generated by Django 5.1.7 on 2025-03-16 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_is_sub_comment_is_reply_remove_comment_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rcomments', to='blog.comment', verbose_name='در پاسخ به'),
        ),
    ]
