# Generated by Django 5.1.7 on 2025-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_like_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-is_active', '-updated'), 'verbose_name': 'بلاگ', 'verbose_name_plural': 'بلاگ ها'},
        ),
        migrations.AlterField(
            model_name='follow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
    ]
