# Generated by Django 5.1.7 on 2025-04-17 16:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_options_alter_follow_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=250, verbose_name='متن کامنت'),
        ),
    ]
